import { Kanit } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'


const oswald = Kanit({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
